language: swift
osx_image: xcode11
script: 
  - xcodebuild -sdk iphonesimulator -project ./SwiftUISampleApp/AttributedTextSample.xcodeproj -scheme AttributedTextSample -destination 'platform=iOS Simulator,name=iPhone XÊ€,OS=13.0' test
after_success:
  - bash <(curl -s https://codecov.io/bash)
